config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'

  resources :projects do
    resources :tasks do
      put :set_status, on: :member
      get :up, on: :member
      get :down, on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :title, :description, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  
  def index
    @projects = Project.all
  end

  def show
    @tasks = Task.where(project_id: @project.id)
  end

  def new
    @project = current_user.projects.new 
  end

  def create
    @project = current_user.projects.new(project_params)
    
    if @project.save 
      flash[:notice] = "Project has been created"
      redirect_to root_path
    else 
      flash[:error] = "Project has not been created"
      render :new
    end 
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated"
      redirect_to root_path
    else 
      flash[:error] = "Project has not been updated"
      render :edit
    end 
  end

  def destroy
    @project.destroy
    flash[:notice] = "Projects has been deleted"
    redirect_to root_path
  end
  private

  def project_params
    params.require(:project).permit(:title, :description, :user_id)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    if @project.tasks.any?
      task = @project.tasks.order(position: :asc).last
      last_task_position = task.position
    else
      last_task_position = 1
    end
    
    @task = @project.tasks.create(tasks_params.merge(position: last_task_position + 1))
    redirect_to project_path(@project)
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    respond_to do |format|
      format.js { render 'edit.js'}
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

  def set_status
    @task = Task.find(params[:id])
    @task.update_attribute(:done, params[:completed])
  end

  def up  
    @project = Project.find(params[:project_id])
    task = Task.find(params[:id])
    redirect_to project_path(@project) if task.position == 1
    previous_task = Task.find_by_position(task.position - 1)
    task.update(position: task.position - 1)
    previous_task.update(position: task.position + 1)
    redirect_to project_path(@project)
  end

  def down 
    @project = Project.find(params[:project_id])
    task = Task.find(params[:id])
    next_task = Task.find_by_position(task.position + 1)
    if next_task.nil?
      redirect_to project_path(@project)
    else
      task.update(position: task.position + 1)
      next_task.update(position: task.position - 1)
      redirect_to project_path(@project)
    end
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :description, :deadline, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectsTasks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, message| %>
        <div class="text-center alert
                    alert-<%= key == 'notice' ? 'success' : 'danger' %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, html: {class: 'form-horizontal'} do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger" id="error-explanation">
     <h4><%= pluralize(@project.errors.count, "error") %>
      prohibited this project from being saved:</h4>

      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-md-5">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: "8" %>
      <br>

      <div class="row" id="links">
        <%= f.submit "Save", class: "btn btn-success" %>
        <%= link_to "Back", root_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
<h2>Edit Project</h2>
</div>
<br>
<div class="row">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class="row"> 
  <header>
  <h2>
    Projects
    <%= link_to "New Project", new_project_path, class: "btn btn-primary pull-right" %>
  </h2> 
</div>

<div class="row">
  <table class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Options</th>
    </tr>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td >
            <%= link_to "Edit", edit_project_path(project), class: "btn btn-xs btn-success" %>
            <%= link_to "Show", project_path(project), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", project_path(project), data: {confirm: 'Are you sure, you want to delete this project?', commit: "Ok" }, method: :delete, class: "btn btn-xs btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<div class="row">
<h2>New Project</h2>
</div>
<br>
<div class="row">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="row">
  <h2>Project</h2>
</div>
<div class="row">
  <div class="col-md-6">  
    <div class="panel panel-primary">
      <div class="panel-heading"><%= @project.title %></div>
  
      <div class="panel-body">
        <strong>Project Desription:</strong>
        <br>
        <p><%= @project.description %></p>
      </div>
    </div>
    <hr>
    <h2>List of Tasks</h2>
    <hr>
    <div class="row">
      <div class="col-md-10 col-md-offset-1" id="tasks_list" > 
        
        <%= render @project.tasks.order(position: :asc) %>
      </div>
    </div>
  </div>
  <div class="col-md-6">  
    <div class="row">
      <div class="col-md-10 col-md-offset-1" id="task_form">  
        <h4>Add New Task</h4>
        <%= render 'tasks/form' %>
      </div>
    </div>
    <hr>
  </div>
</div>
<hr>
<div class="row" id="links">
  <%= link_to "Back", root_path, class: "btn btn-default" %>
</div>
<hr>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build], html: {class: 'form-horizontal new_task'}) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title, class: 'form-control'  %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control'  %>
    <br>
    <%= f.label :deadline %>
    <%= f.date_select :deadline, class: 'form-control'  %>

    <%= f.hidden_field :user_id, value: @project.user_id %>

    <p><%= f.submit "Add Task", class: 'btn btn-success pull-right add_task', disabled: true %></p>
  </div>
<%end%>

app/views/tasks/_task.html.erb
<div class="panel panel-primary" id="task_<%= task.id %>">
  <div class="panel-heading"><%= task.title %></div>

  <div class="panel-body">
    <strong>Task Desription:</strong>
    <br>
    <p><%= task.description %></p>
    <label for="deadline">Deadline:</label>
    <p><%= task.deadline.strftime('%d %B, %Y') %></p>
    <strong>Done <%= check_box_tag 'completed', task.id , task.done, class: "task-check", 'data-update-url': set_status_project_task_path(@project, task) %></strong>
  </div>
  <div class="panel-footer">
    <%= link_to "Edit",  edit_project_task_path(task, project_id: task.project_id), class: "btn btn-success edit_task" ,id: "task_#{task.id}", remote: true %>
    <%= link_to "Delete",  project_task_path(task, project_id: task.project_id), method: :delete, data: {confirm: "Are you sure", commit: "Yes"}, class: "btn btn-danger" %>

    <%= link_to "Up", up_project_task_path(@project, task), class: "btn btn-success" %>
    <%= link_to "Down", down_project_task_path(@project, task), class: "btn btn-success" %>
  </div>
</div>

app/views/tasks/_task_form.html.erb
<div class="panel panel-primary">
  <%= form_for(@task, url: project_task_path, remote: true) do |f| %>  
    <div class="panel-heading">
      Title: <%= f.text_field :title, id: 'edit_title' %> 
    </div>

    <div class="panel-body">
      <strong>Task Desription:</strong>
      <br>
      <p><%= f.text_area :description%></p>
      <p><%= f.label :deadline %>
      <%= f.date_select :deadline, class: 'form-control'  %></p>
    </div>
    <div class="panel-footer">
      <%= f.submit "Save", class: 'btn btn-success task_save' %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.js.erb
$('.panel.panel-primary#task_<%= @task.id %>').replaceWith("<%= j render( partial: 'task_form') %>"); 